import{supabase}from'../../lib/supabase';import type{Resource,ResourceCategory}from'./resource';import{isPowerPoint}from'./resource';
const bucket=supabase.storage.from('teaching-resources');const map=(r:any):Resource=>({id:r.id,title:r.title,description:r.description??'',category:r.category,originalFileName:r.original_file_name,fileType:r.file_type,mimeType:r.mime_type,fileSize:Number(r.file_size),storagePath:r.storage_path??'',previewStoragePath:r.preview_storage_path??'',previewFileName:r.preview_file_name??'',previewMimeType:r.preview_mime_type??'',previewFileSize:Number(r.preview_file_size??0),createdAt:r.created_at,updatedAt:r.updated_at});
const metadata=(input:{title:string;description:string;category:ResourceCategory})=>({title:input.title.trim(),description:input.description.trim()||null,category:input.category});
export async function getResources(){const{data,error}=await supabase.from('resources').select('*').order('created_at',{ascending:false});if(error)throw error;return(data??[]).map(map)}
export async function getResource(id:string){const{data,error}=await supabase.from('resources').select('*').eq('id',id).single();if(error)throw error;return map(data)}
export async function createResource(input:{title:string;description:string;category:ResourceCategory},file:File,preview?:File|null){const ext=file.name.split('.').pop()?.toLowerCase()??'';const{data,error}=await supabase.from('resources').insert({...metadata(input),original_file_name:file.name,file_type:ext,mime_type:file.type||'application/octet-stream',file_size:file.size}).select('id').single();if(error)throw error;const originalPath=`${data.id}/original-${crypto.randomUUID()}.${ext}`,previewPath=preview?`${data.id}/preview-${crypto.randomUUID()}.pdf`:'';const uploaded:string[]=[];try{const originalUpload=await bucket.upload(originalPath,file,{upsert:false,contentType:file.type});if(originalUpload.error)throw originalUpload.error;uploaded.push(originalPath);if(preview){const previewUpload=await bucket.upload(previewPath,preview,{upsert:false,contentType:'application/pdf'});if(previewUpload.error)throw previewUpload.error;uploaded.push(previewPath)}const{error:updateError}=await supabase.from('resources').update({storage_path:originalPath,...(preview?{preview_storage_path:previewPath,preview_file_name:preview.name,preview_mime_type:'application/pdf',preview_file_size:preview.size}:{})}).eq('id',data.id);if(updateError)throw updateError;return data.id as string}catch(reason){if(uploaded.length)await bucket.remove(uploaded);await supabase.from('resources').delete().eq('id',data.id);throw reason}}
export async function updateResource(id:string,input:{title:string;description:string;category:ResourceCategory}){const{error}=await supabase.from('resources').update(metadata(input)).eq('id',id);if(error)throw error}
export async function uploadResourcePreview(resource:Resource,file:File){const path=`${resource.id}/preview-${crypto.randomUUID()}.pdf`;const{error:uploadError}=await bucket.upload(path,file,{upsert:false,contentType:'application/pdf'});if(uploadError)throw uploadError;const{error:updateError}=await supabase.from('resources').update({preview_storage_path:path,preview_file_name:file.name,preview_mime_type:'application/pdf',preview_file_size:file.size}).eq('id',resource.id);if(updateError){await bucket.remove([path]);throw updateError}if(resource.previewStoragePath)await bucket.remove([resource.previewStoragePath])}
export async function deleteResource(r:Resource){const paths=[r.storagePath,r.previewStoragePath].filter(Boolean);if(paths.length){const{error}=await bucket.remove(paths);if(error)throw error}const{error}=await supabase.from('resources').delete().eq('id',r.id);if(error)throw error}
async function signedPath(path:string,download?:string){const{data,error}=await bucket.createSignedUrl(path,3600,download?{download}:undefined);if(error)throw error;return data.signedUrl}
export async function signedResourceUrl(r:Resource,download=false){return signedPath(r.storagePath,download?r.originalFileName:undefined)}
export async function signedPreviewUrl(r:Resource,download=false){if(!r.previewStoragePath)throw new Error('Mobile preview is not available.');return signedPath(r.previewStoragePath,download?r.previewFileName:undefined)}
export async function viewableResourceUrl(r:Resource){return isPowerPoint(r)?signedPreviewUrl(r):signedResourceUrl(r)}
export async function downloadResourceBlob(r:Resource){const response=await fetch(await viewableResourceUrl(r));if(!response.ok)throw new Error('Resource download failed.');return response.blob()}
