import { useEffect, useRef, useState } from "react";
import { CalendarDays, Clock, MapPin, Users } from "lucide-react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import Button from "../components/ui/Button";
import Input from "../components/ui/Input";
import Select from "../components/ui/Select";
import Textarea from "../components/ui/Textarea";
import { registrationAvailability, type PublicEvent } from "../features/events/event";
import { getPublicEvent, registerForEvent, type RegistrationInput } from "../features/events/eventService";
import "./admin/EventEnhancements.css";

const blank: RegistrationInput = { firstName:"", lastName:"", mobile:"", email:"", gender:"", age:"", notes:"" };
const namePattern = /^[\p{L}]+(?:[ '-][\p{L}]+)*$/u;

export default function EventRegistrationPage() {
  const { slug="" } = useParams(); const [searchParams] = useSearchParams(); const isDesk = searchParams.get("desk") === "1";
  const [event,setEvent] = useState<PublicEvent|null>(null), [form,setForm] = useState(blank), [loading,setLoading] = useState(true), [saving,setSaving] = useState(false), [error,setError] = useState(""), [fieldErrors,setFieldErrors] = useState<Record<string,string>>({}), [success,setSuccess] = useState<any>(null);
  const firstRef = useRef<HTMLInputElement>(null);
  useEffect(() => { void (async () => { try { setEvent(await getPublicEvent(slug)); } catch { setError("This event could not be loaded."); } finally { setLoading(false); } })(); }, [slug]);
  function change(key:keyof RegistrationInput,value:string){setForm(v=>({...v,[key]:value}));setFieldErrors(v=>({...v,[key]:""}));}
  function validate(){const e:Record<string,string>={};if(!form.firstName.trim())e.firstName="First name is required.";else if(!namePattern.test(form.firstName.trim()))e.firstName="Use letters, spaces, apostrophes, or hyphens only.";if(!form.lastName.trim())e.lastName="Last name is required.";else if(!namePattern.test(form.lastName.trim()))e.lastName="Use letters, spaces, apostrophes, or hyphens only.";if(form.email&&!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(form.email))e.email="Enter a valid email address.";if(form.mobile&&!/^(?:09\d{9}|\+639\d{9})$/.test(form.mobile))e.mobile="Use 09xxxxxxxxx or +639xxxxxxxxx.";if(form.age&&(Number(form.age)<0||Number(form.age)>120))e.age="Enter an age from 0 to 120.";setFieldErrors(e);if(e.firstName)firstRef.current?.focus();return !Object.keys(e).length;}
  async function submit(e:React.FormEvent){e.preventDefault();if(!validate())return;setSaving(true);setError("");try{setSuccess(await registerForEvent(slug,form));setForm({...blank});}catch(reason:any){const message=reason?.message??"Registration could not be completed.";setError(message.includes("already exists")?"A registration already exists for these details.":message);}finally{setSaving(false);}}
  function nextAttendee(){setForm({...blank});setFieldErrors({});setError("");setSuccess(null);requestAnimationFrame(()=>firstRef.current?.focus());}
  if(loading)return <main className="public-event-state">Loading event...</main>;
  if(!event)return <main className="public-event-state"><h1>Event unavailable</h1><p>{error||"This event is not published or no longer available."}</p><Link to="/">Return to homepage</Link></main>;
  const availability=registrationAvailability(event),remaining=event.capacity===null?null:Math.max(0,event.capacity-Number(event.registered_count));
  if(success)return <main className="public-event-page"><section className="public-event-success"><div>✓</div><h1>Registration successful</h1><p>The registration has been received. No account was created.</p><dl><div><dt>Event</dt><dd>{success.event_name}</dd></div><div><dt>Date &amp; Time</dt><dd>{new Date(`${success.event_date}T00:00:00`).toLocaleDateString(undefined,{dateStyle:"long"})} · {String(success.starts_at).slice(0,5)}</dd></div><div><dt>Location</dt><dd>{success.location}</dd></div>{!isDesk&&<div><dt>Registrant</dt><dd>{success.registrant_name}</dd></div>}</dl>{isDesk?<Button onClick={nextAttendee}>Register Next Attendee</Button>:<Button to="/">Return to Homepage</Button>}</section></main>;
  return <main className={`public-event-page${isDesk?" registration-desk-page":""}`}>{isDesk&&<div className="registration-desk-banner"><strong>Registration Desk</strong><span>Shared-device mode · each completed form is cleared</span></div>}{event.banner_url&&<img className="public-event-banner" src={event.banner_url} alt=""/>}<section className="public-event-card public-event-intro"><span className={`event-registration-state event-registration-${availability.code}`}>{availability.label}</span><h1>{event.name}</h1><p>{event.description||"Join us for this GGCCC event."}</p><div className="public-event-facts"><span><CalendarDays/>{new Date(`${event.event_date}T00:00:00`).toLocaleDateString(undefined,{dateStyle:"long"})}</span><span><Clock/>{event.starts_at.slice(0,5)}{event.ends_at?`–${event.ends_at.slice(0,5)}`:""}</span><span><MapPin/>{event.location}</span>{event.capacity!==null&&<span><Users/>{remaining} of {event.capacity} spaces remaining</span>}</div></section><section className="public-event-card"><h2>{isDesk?"Register Attendee":"Register"}</h2>{!availability.open?<div className="public-registration-unavailable"><strong>{availability.label}</strong><p>Please contact GGCCC if you need assistance.</p></div>:<form className="registration-form" onSubmit={submit} noValidate>{error&&<div className="events-error">{error}</div>}<div className="registration-form-grid"><Field label="First Name *" error={fieldErrors.firstName}><Input ref={firstRef} autoComplete={isDesk?"off":"given-name"} value={form.firstName} onChange={e=>change("firstName",e.target.value)}/></Field><Field label="Last Name *" error={fieldErrors.lastName}><Input autoComplete={isDesk?"off":"family-name"} value={form.lastName} onChange={e=>change("lastName",e.target.value)}/></Field><Field label="Mobile Number" error={fieldErrors.mobile}><Input type="tel" inputMode="tel" autoComplete={isDesk?"off":"tel"} value={form.mobile} onChange={e=>change("mobile",e.target.value)}/></Field><Field label="Email" error={fieldErrors.email}><Input type="email" autoComplete={isDesk?"off":"email"} value={form.email} onChange={e=>change("email",e.target.value)}/></Field><Field label="Gender"><Select value={form.gender} onChange={e=>change("gender",e.target.value)}><option value="">Prefer not to say</option><option>Male</option><option>Female</option></Select></Field><Field label="Age" error={fieldErrors.age}><Input type="number" inputMode="numeric" min="0" max="120" value={form.age} onChange={e=>change("age",e.target.value)}/></Field><label className="registration-form-wide"><span>Notes</span><Textarea rows={3} value={form.notes} onChange={e=>change("notes",e.target.value)}/></label></div><Button type="submit" disabled={saving}>{saving?"Registering...":"Complete Registration"}</Button><p className="public-registration-privacy">Details are used only for this event. Registration does not create a church Member account.</p></form>}</section></main>;
}

function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label><span>{label}</span>{children}{error&&<small className="field-error">{error}</small>}</label>;}
