import { supabase } from "../../lib/supabase";
import type{ChurchEvent,EventInput,EventRegistration,PublicEvent}from"./event";
const eventSelect=`id,name,slug,description,event_date,starts_at,ends_at,location,capacity,registration_enabled,registration_open_at,registration_close_at,status,notes,banner_url,archived_at,created_at,contact:members!events_contact_person_member_id_fkey(id,first_name,last_name),registrations:event_registrations(id,member_id,first_name,last_name,mobile,email,gender,age,notes,status,registered_at,checked_in_at)`;
function mapRegistration(r:any):EventRegistration{return{id:r.id,memberId:r.member_id,firstName:r.first_name,lastName:r.last_name,mobile:r.mobile??"",email:r.email??"",gender:r.gender??"",age:r.age,notes:r.notes??"",status:r.status,registeredAt:r.registered_at,checkedInAt:r.checked_in_at};}
function mapEvent(r:any):ChurchEvent{const c=Array.isArray(r.contact)?r.contact[0]:r.contact;return{id:r.id,name:r.name,slug:r.slug,description:r.description??"",eventDate:r.event_date,startsAt:r.starts_at,endsAt:r.ends_at??"",location:r.location,capacity:r.capacity,registrationEnabled:r.registration_enabled,registrationOpenAt:r.registration_open_at??"",registrationCloseAt:r.registration_close_at??"",status:r.status,contactPerson:c?{id:c.id,name:`${c.first_name} ${c.last_name}`.trim()}:null,notes:r.notes??"",bannerUrl:r.banner_url??"",archivedAt:r.archived_at,createdAt:r.created_at,registrations:(r.registrations??[]).map(mapRegistration)};}
export async function getEvents(){const{data,error}=await supabase.from("events").select(eventSelect).order("event_date");if(error)throw error;return(data??[]).map(mapEvent);}
export async function getEvent(id:string){const{data,error}=await supabase.from("events").select(eventSelect).eq("id",id).single();if(error)throw error;return mapEvent(data);}
export async function getEventContacts(){const{data,error}=await supabase.from("members").select("id,first_name,last_name,membership_status").order("last_name");if(error)throw error;return(data??[]).map(r=>({id:r.id,name:`${r.first_name} ${r.last_name}`.trim(),active:r.membership_status!=="Inactive"}));}
const nil=(v:string)=>v.trim()||null;const iso=(v:string)=>v?new Date(v).toISOString():null;
function payload(i:EventInput){return{name:i.name.trim(),slug:i.slug.trim().toLowerCase(),description:nil(i.description),event_date:i.eventDate,starts_at:i.startsAt,ends_at:i.endsAt||null,location:i.location.trim(),capacity:i.capacity===""?null:Number(i.capacity),registration_enabled:i.registrationEnabled,registration_open_at:iso(i.registrationOpenAt),registration_close_at:iso(i.registrationCloseAt),status:i.status,contact_person_member_id:i.contactPersonMemberId||null,notes:nil(i.notes),banner_url:nil(i.bannerUrl),archived_at:i.status==="archived"?new Date().toISOString():null};}
export async function saveEvent(input:EventInput,id?:string){const q=id?supabase.from("events").update(payload(input)).eq("id",id):supabase.from("events").insert(payload(input));const{data,error}=await q.select("id").single();if(error)throw error;return data.id;}
export async function updateEventStatus(id:string,status:ChurchEvent["status"]){const{data:auth}=await supabase.auth.getUser();const{error}=await supabase.from("events").update({status,archived_at:status==="archived"?new Date().toISOString():null,archived_by:status==="archived"?auth.user?.id??null:null}).eq("id",id);if(error)throw error;}
export async function updateRegistration(id:string,patch:{status?:string;checked_in_at?:string|null;checked_in_by?:string|null}){const{error}=await supabase.from("event_registrations").update(patch).eq("id",id);if(error)throw error;}
export async function checkInRegistration(id:string,checkedIn:boolean){const{data}=await supabase.auth.getUser();await updateRegistration(id,{checked_in_at:checkedIn?new Date().toISOString():null,checked_in_by:checkedIn?data.user?.id??null:null});}
export async function getPublicEvent(slug:string):Promise<PublicEvent|null>{const{data,error}=await supabase.rpc("get_public_event",{p_slug:slug});if(error)throw error;return data as PublicEvent|null;}
export interface RegistrationInput{firstName:string;lastName:string;mobile:string;email:string;gender:string;age:string;notes:string;}
export async function registerForEvent(slug:string,input:RegistrationInput){const{data,error}=await supabase.rpc("register_for_event",{p_event_slug:slug,p_first_name:input.firstName,p_last_name:input.lastName,p_mobile:input.mobile||null,p_email:input.email||null,p_gender:input.gender||null,p_age:input.age===""?null:Number(input.age),p_notes:input.notes||null});if(error)throw error;return data;}
