import { useCallback, useEffect, useState } from "react";
import { Archive, CalendarDays, UserRound, Wrench } from "lucide-react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import Modal from "../../components/Modal";
import Button from "../../components/ui/Button";
import Input from "../../components/ui/Input";
import Select from "../../components/ui/Select";
import Textarea from "../../components/ui/Textarea";
import { useAuth } from "../../features/auth/auth";
import { CONDITION_LABELS, MAINTENANCE_STATUS_LABELS, MAINTENANCE_TYPE_LABELS, TRACKING_LABELS, type EquipmentItem, type MaintenanceStatus, type MaintenanceType } from "../../features/equipment/equipment";
import { addEquipmentMaintenance, archiveEquipmentItem, getEquipmentItem } from "../../features/equipment/equipmentService";

function money(value: number | null) { return value === null ? "Not recorded" : new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(value); }
function Detail({ label, value }: {label:string;value:React.ReactNode}) { return <div><dt>{label}</dt><dd>{value || "Not recorded"}</dd></div>; }
export default function EquipmentDetail() {
  const { id } = useParams(); const navigate = useNavigate(); const location = useLocation(); const { hasPermission } = useAuth(); const canManage = hasPermission("equipment.manage");
  const [item,setItem]=useState<EquipmentItem|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [message,setMessage]=useState(location.state?.success ?? ""); const [archiveOpen,setArchiveOpen]=useState(false); const [maintenanceOpen,setMaintenanceOpen]=useState(false); const [saving,setSaving]=useState(false);
  const [maintenance,setMaintenance]=useState({maintenanceDate:new Date().toISOString().slice(0,10),type:"inspection" as MaintenanceType,status:"completed" as MaintenanceStatus,cost:"",notes:""});
  const load=useCallback(async()=>{if(!id)return;setLoading(true);setError("");try{setItem(await getEquipmentItem(id));}catch{setError("Equipment item could not be loaded.");}finally{setLoading(false);}},[id]); useEffect(()=>{void load();},[load]);
  async function archive(){if(!id)return;setSaving(true);try{await archiveEquipmentItem(id);navigate("/admin/equipment",{state:{success:"Equipment item archived."}});}catch{setError("Equipment item could not be archived.");setSaving(false);}}
  async function addMaintenance(event:React.FormEvent){event.preventDefault();if(!id)return;setSaving(true);setError("");try{await addEquipmentMaintenance({equipmentItemId:id,...maintenance});setMaintenanceOpen(false);setMaintenance({maintenanceDate:new Date().toISOString().slice(0,10),type:"inspection",status:"completed",cost:"",notes:""});await load();setMessage("Maintenance record added.");}catch{setError("Maintenance record could not be saved.");}finally{setSaving(false);}}
  if(loading)return <p className="equipment-state">Loading equipment...</p>; if(error&&!item)return <div className="equipment-state equipment-error">{error}<Button variant="secondary" onClick={()=>void load()}>Try again</Button></div>; if(!item)return null;
  return <div className="equipment-detail-page"><button className="equipment-back" onClick={()=>navigate("/admin/equipment")}>← Back to Equipment</button>{message&&<div className="equipment-success">{message}<button onClick={()=>setMessage("")}>Dismiss</button></div>}
    <header className="equipment-detail-header"><div><span className={`equipment-badge equipment-badge-${item.condition}`}>{CONDITION_LABELS[item.condition]}</span><h1>{item.name}</h1><p>{item.description||"No description recorded."}</p></div>{canManage&&!item.archivedAt&&<div><Button to={`/admin/equipment/${item.id}/edit`}>Edit Item</Button><Button variant="danger" onClick={()=>setArchiveOpen(true)}>Archive</Button></div>}</header>
    {item.archivedAt&&<div className="equipment-archived-notice"><Archive size={18}/>This equipment item is archived and excluded from the active inventory.</div>}
    <div className="equipment-detail-grid">
      <section className="equipment-panel"><h2>General</h2><dl className="equipment-detail-list"><Detail label="Category" value={item.category}/><Detail label="Tracking Type" value={TRACKING_LABELS[item.trackingType]}/><Detail label="Quantity" value={item.quantity}/><Detail label="Location" value={item.location}/></dl></section>
      <section className="equipment-panel"><h2>Current Status</h2><dl className="equipment-detail-list"><Detail label="Condition" value={CONDITION_LABELS[item.condition]}/><Detail label="Custodian" value={item.custodian?<button className="equipment-member-link" onClick={()=>navigate(`/admin/members/${item.custodian?.id}`)}><UserRound size={16}/>{item.custodian.name}</button>:"Not assigned"}/><Detail label="Last Updated" value={new Date(item.updatedAt).toLocaleDateString()}/></dl></section>
      <section className="equipment-panel"><h2>Asset Information</h2><dl className="equipment-detail-list"><Detail label="Brand" value={item.brand}/><Detail label="Model" value={item.model}/><Detail label="Serial Number" value={item.serialNumber}/><Detail label="Asset Tag" value={item.assetTag}/></dl></section>
      <section className="equipment-panel"><h2>Purchase Information</h2><dl className="equipment-detail-list"><Detail label="Purchase Date" value={item.purchaseDate?new Date(`${item.purchaseDate}T00:00:00`).toLocaleDateString():"Not recorded"}/><Detail label="Purchase Cost" value={money(item.purchaseCost)}/><Detail label="Notes" value={item.notes}/></dl></section>
    </div>
    <section className="equipment-panel equipment-maintenance"><div className="equipment-section-heading"><div><h2>Maintenance / Repair History</h2><p>Inspections, repairs, parts, and maintenance recorded for this item.</p></div>{canManage&&!item.archivedAt&&<Button onClick={()=>setMaintenanceOpen(true)}><Wrench size={16}/> Add Record</Button>}</div>{item.maintenance.length===0?<p className="equipment-state">No maintenance or repair history recorded.</p>:<div className="equipment-maintenance-list">{item.maintenance.map(record=><article key={record.id}><CalendarDays size={20}/><div><strong>{MAINTENANCE_TYPE_LABELS[record.type]}</strong><span>{new Date(`${record.maintenanceDate}T00:00:00`).toLocaleDateString()} · {MAINTENANCE_STATUS_LABELS[record.status]}</span><p>{record.notes||"No notes recorded."}</p></div><b>{money(record.cost)}</b></article>)}</div>}</section>
    <Modal open={archiveOpen} title="Archive Equipment Item" onClose={()=>!saving&&setArchiveOpen(false)}><p>Archive <strong>{item.name}</strong>? It will leave the active inventory but remain available in the archived view with its maintenance history.</p><div className="equipment-modal-actions"><Button variant="secondary" disabled={saving} onClick={()=>setArchiveOpen(false)}>Cancel</Button><Button variant="danger" disabled={saving} onClick={()=>void archive()}>{saving?"Archiving...":"Archive Item"}</Button></div></Modal>
    <Modal open={maintenanceOpen} title="Add Maintenance Record" onClose={()=>!saving&&setMaintenanceOpen(false)}><form className="equipment-modal-form" onSubmit={addMaintenance}><label><span>Date *</span><Input required type="date" value={maintenance.maintenanceDate} onChange={e=>setMaintenance(v=>({...v,maintenanceDate:e.target.value}))}/></label><label><span>Type *</span><Select value={maintenance.type} onChange={e=>setMaintenance(v=>({...v,type:e.target.value as MaintenanceType}))}>{Object.entries(MAINTENANCE_TYPE_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></label><label><span>Status *</span><Select value={maintenance.status} onChange={e=>setMaintenance(v=>({...v,status:e.target.value as MaintenanceStatus}))}>{Object.entries(MAINTENANCE_STATUS_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></label><label><span>Cost</span><Input type="number" min="0" step="0.01" value={maintenance.cost} onChange={e=>setMaintenance(v=>({...v,cost:e.target.value}))}/></label><label><span>Notes</span><Textarea rows={4} value={maintenance.notes} onChange={e=>setMaintenance(v=>({...v,notes:e.target.value}))}/></label><div className="equipment-modal-actions"><Button type="button" variant="secondary" disabled={saving} onClick={()=>setMaintenanceOpen(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving?"Saving...":"Save Record"}</Button></div></form></Modal>
  </div>;
}
