import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import Button from "../../components/ui/Button";
import Input from "../../components/ui/Input";
import SearchableSelect from "../../components/ui/SearchableSelect";
import Select from "../../components/ui/Select";
import Textarea from "../../components/ui/Textarea";
import { CONDITION_LABELS, TRACKING_LABELS, type EquipmentCondition, type EquipmentInput, type EquipmentTrackingType } from "../../features/equipment/equipment";
import { getEquipmentCategories, getEquipmentCustodians, getEquipmentItem, saveEquipmentItem } from "../../features/equipment/equipmentService";

const empty: EquipmentInput = { name: "", trackingType: "individual", categoryId: "", quantity: 1, condition: "working", description: "", location: "", custodianMemberId: "", brand: "", model: "", serialNumber: "", assetTag: "", purchaseDate: "", purchaseCost: "", notes: "" };
export default function EquipmentForm() {
  const { id } = useParams(); const navigate = useNavigate();
  const [form, setForm] = useState<EquipmentInput>(empty); const [categories, setCategories] = useState<{id:string;name:string}[]>([]); const [custodians, setCustodians] = useState<{id:string;name:string;active:boolean}[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void (async () => { try { const [nextCategories, nextCustodians, item] = await Promise.all([getEquipmentCategories(), getEquipmentCustodians(), id ? getEquipmentItem(id) : Promise.resolve(null)]); setCategories(nextCategories.filter((value) => value.isActive)); setCustodians(nextCustodians); if (item) setForm({ name:item.name, trackingType:item.trackingType, categoryId:item.categoryId, quantity:item.quantity, condition:item.condition, description:item.description, location:item.location, custodianMemberId:item.custodian?.id ?? "", brand:item.brand, model:item.model, serialNumber:item.serialNumber, assetTag:item.assetTag, purchaseDate:item.purchaseDate, purchaseCost:item.purchaseCost?.toString() ?? "", notes:item.notes }); else if (nextCategories.length) setForm((current) => ({...current, categoryId:nextCategories[0].id})); } catch { setError("Equipment form data could not be loaded."); } finally { setLoading(false); } })(); }, [id]);
  function change<K extends keyof EquipmentInput>(key: K, value: EquipmentInput[K]) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!form.name.trim() || !form.categoryId || form.quantity < 1) { setError("Complete all required fields with valid values."); return; } setSaving(true); setError(""); try { const savedId = await saveEquipmentItem(form, id); navigate(`/admin/equipment/${savedId}`, { state: { success: id ? "Equipment item updated." : "Equipment item added." } }); } catch (reason: any) { setError(reason?.code === "23505" ? "That asset tag is already in use." : "Equipment item could not be saved. Please try again."); } finally { setSaving(false); } }
  if (loading) return <p className="equipment-state">Loading equipment form...</p>;
  return <div className="equipment-form-page"><header><button onClick={() => navigate(-1)}>← Back</button><h1>{id ? "Edit Equipment" : "Add Equipment"}</h1><p>Record an individual asset or a quantity-based church item.</p></header><form className="equipment-form" onSubmit={submit}>{error && <div className="equipment-error">{error}</div>}
    <section><h2>General</h2><div className="equipment-form-grid"><label><span>Item Name *</span><Input required value={form.name} onChange={(e) => change("name",e.target.value)} /></label><label><span>Tracking Type *</span><Select value={form.trackingType} onChange={(e) => change("trackingType",e.target.value as EquipmentTrackingType)}>{Object.entries(TRACKING_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></label><label><span>Category *</span><Select required value={form.categoryId} onChange={(e)=>change("categoryId",e.target.value)}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></label><label><span>Quantity *</span><Input type="number" min="1" disabled={form.trackingType==="individual"} value={form.trackingType==="individual"?1:form.quantity} onChange={(e)=>change("quantity",Number(e.target.value))} /></label><label><span>Condition *</span><Select value={form.condition} onChange={(e)=>change("condition",e.target.value as EquipmentCondition)}>{Object.entries(CONDITION_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></label><label><span>Location</span><Input value={form.location} onChange={(e)=>change("location",e.target.value)} placeholder="e.g. Tech Booth" /></label><label className="equipment-form-wide"><span>Description</span><Textarea rows={3} value={form.description} onChange={(e)=>change("description",e.target.value)} /></label><label className="equipment-form-wide"><span>Custodian (optional)</span><SearchableSelect options={[{id:"",label:"No custodian"},...custodians.map(c=>({id:c.id,label:`${c.name}${c.active?"":" (Inactive)"}`}))]} value={form.custodianMemberId} onChange={(value)=>change("custodianMemberId",value)} placeholder="No custodian" /></label></div></section>
    <section><h2>Asset Information</h2><div className="equipment-form-grid"><label><span>Brand</span><Input value={form.brand} onChange={(e)=>change("brand",e.target.value)} /></label><label><span>Model</span><Input value={form.model} onChange={(e)=>change("model",e.target.value)} /></label><label><span>Serial Number</span><Input value={form.serialNumber} onChange={(e)=>change("serialNumber",e.target.value)} /></label><label><span>Asset Tag</span><Input value={form.assetTag} onChange={(e)=>change("assetTag",e.target.value)} /></label></div></section>
    <section><h2>Purchase &amp; Notes</h2><div className="equipment-form-grid"><label><span>Purchase Date</span><Input type="date" value={form.purchaseDate} onChange={(e)=>change("purchaseDate",e.target.value)} /></label><label><span>Purchase Cost</span><Input type="number" min="0" step="0.01" value={form.purchaseCost} onChange={(e)=>change("purchaseCost",e.target.value)} /></label><label className="equipment-form-wide"><span>Notes</span><Textarea rows={4} value={form.notes} onChange={(e)=>change("notes",e.target.value)} /></label></div></section>
    <div className="equipment-form-actions"><Button type="button" variant="secondary" onClick={()=>navigate(-1)}>Cancel</Button><Button type="submit" disabled={saving}>{saving?"Saving...":"Save Item"}</Button></div>
  </form></div>;
}
