import { useEffect, useMemo, useState } from "react";
import { Download, Eye, Files, Plus, Search, Share2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import Button from "../../components/ui/Button";
import Input from "../../components/ui/Input";
import { useAuth } from "../../features/auth/auth";
import { CATEGORY_LABELS, formatFileSize, resourceKind, type Resource, type ResourceCategory } from "../../features/resources/resource";
import { getResources, signedResourceUrl } from "../../features/resources/resourceService";
const FILTERS: ("all" | ResourceCategory)[] = ["all", "cell_discussion", "training", "ministry", "other"];
export default function Resources() {
 const navigate=useNavigate(),{hasPermission}=useAuth(),canManage=hasPermission("resources.manage"); const[items,setItems]=useState<Resource[]>([]),[search,setSearch]=useState(""),[category,setCategory]=useState<"all"|ResourceCategory>("all"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{void getResources().then(setItems).catch(()=>setError("Resources could not be loaded.")).finally(()=>setLoading(false))},[]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return items.filter(x=>(category==="all"||x.category===category)&&(!q||[x.title,x.description,CATEGORY_LABELS[x.category],x.originalFileName].some(v=>v.toLowerCase().includes(q))))},[items,search,category]);
 async function download(e:React.MouseEvent,r:Resource){e.stopPropagation();window.location.assign(await signedResourceUrl(r,true))} async function share(e:React.MouseEvent,r:Resource){e.stopPropagation();const url=`${location.origin}/admin/resources/${r.id}`;if(navigator.share)await navigator.share({title:r.title,url});else{await navigator.clipboard.writeText(url);alert("Resource link copied.")}}
 return <div className="res-page"><header className="res-header"><div><h1>Resources</h1><p>Teaching materials, lessons and ministry resources.</p></div>{canManage&&<Button to="/admin/resources/new"><Plus size={17}/>Add Resource</Button>}</header><section className="res-panel"><label className="res-search"><Search size={18}/><Input placeholder="Search resources..." aria-label="Search resources" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="res-filters">{FILTERS.map(v=><button key={v} className={category===v?"active":""} onClick={()=>setCategory(v)}>{v==="all"?"All":CATEGORY_LABELS[v]}</button>)}</div>{error&&<div className="res-error">{error}</div>}{loading?<p className="res-state">Loading resources...</p>:visible.length===0?<div className="res-empty"><Files size={44}/><strong>{items.length?"No matching resources.":"No resources yet."}</strong><p>{items.length?"Try another search or category.":"Upload teaching materials, lessons and presentations for church leaders."}</p>{canManage&&!items.length&&<Button to="/admin/resources/new"><Plus size={17}/>Add Resource</Button>}</div>:<div className="res-grid">{visible.map(r=><article key={r.id} onClick={()=>navigate(`/admin/resources/${r.id}`)}><span className="res-category">{CATEGORY_LABELS[r.category]}</span><h2>{r.title}</h2><p>{r.description||r.originalFileName}</p><small>{resourceKind(r)} • {formatFileSize(r.fileSize)}</small><div><Button onClick={e=>{e.stopPropagation();navigate(`/admin/resources/${r.id}`)}}><Eye size={16}/>View</Button><Button variant="secondary" onClick={e=>void download(e,r)}><Download size={16}/>Download</Button><Button variant="secondary" onClick={e=>void share(e,r)}><Share2 size={16}/>Share</Button></div></article>)}</div>}</section></div>;
}
